name: deep_defender
description: Real-time defense against deep fakes.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto_keys: ^0.1.4
  fft: ^0.3.0
  flutter_launcher_icons: "^0.8.1"
  mic_stream: ^0.4.0
  permission_handler: ^5.1.0+2
  pointycastle: ^2.0.1
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  test: ^1.15.7
  qr_flutter: ^3.1.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
