# Copyright 2021 The Deep Defender Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: deep_defender
description: Real-time defense against deep fakes.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto_keys: ^0.3.0
  flutter_audio_capture: ^1.1.6
  flutter_launcher_icons: ^0.9.2
  permission_handler: ^10.0.0
  pointycastle: ^3.5.2
  share_plus: ^4.0.3
  shared_preferences: ^2.0.13
  test: ^1.19.5
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.4
  fftea: ^1.4.1
  wav: ^1.3.0
  pem: ^2.0.4
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
