# Copyright 2023 The Deep Defender Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ stable ]
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - name: Install dependencies
      id: install
      run: flutter pub upgrade
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      if: always() && steps.install.outcome == 'success'
    - name: Check analysis
      run: flutter analyze --fatal-infos
      if: always() && steps.install.outcome == 'success'

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ stable, beta ]
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - name: Install dependencies
      run: flutter pub upgrade
    - name: Run tests
      run: flutter test

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - name: Install dependencies
      run: flutter pub upgrade
    - name: Install coverage
      run: flutter pub global activate coverage
    - name: Run tests and gather coverage
      run: flutter pub global run coverage:test_with_coverage
    - name: Upload coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
